name: Docker Build All Services

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'

jobs:
  test-Classical_Networking_Workflow:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ secrets.TOKEN }}
    - name: Conda Build
      run: |
        cd Classical_Networking_Workflow
        mamba create -n test -f ./bin/conda_env.yml

